runtime: nodejs14
# api_version: 1
# threadsafe: true
# handlers:
# - url: /
#   static_files: www/index.html
#   upload: www/index.html
# - url: /(.*)
#   static_files: www/index.html
#   upload: www/index.html
# - url: /
#   static_dir: www

